### ISSUE TITLE
ANSI Support: keybinding issues for Ctrl+Shift+C

### ISSUE THREAD

**Issue by mihnita** [eclipse-platform/eclipse.platform.debug#65] opened 2022-08-09 14:54 UTC
Understand where the keybinding conflicts with Java Stack Trace console are coming from - we have not just "one" console, but lot of different consoles, so if the keybinding issues appeared in one, they will also appear in other one for sure.

**Comment by mihnita** [comment] 2022-08-09 14:54
Please assign to me (I don't have the right to do it myself)
Thanks,
M.

**Comment by laeubi** [comment] 2022-08-09 16:02
@vogella WDYT about making @mihnita a platform committer?

**Comment by mihnita** [comment] 2022-08-10 02:44
OK, (kind of) got it.
Sometimes 90% of fixing a bug is reproducing it :-)

The problems was no me not knowing where to look for the log, it was that the conflict is not reported on Windows.

Trying in on Linux the conflict is in the log, and also in the Preferences -- General -- Keys -- "Conflicts" panel on the right
(as described here https://github.com/eclipse-platform/eclipse.platform.debug/issues/57#issuecomment-1209099937)

But I think Linux is wrong.

The contexts there the hotkeys are supposed to be active are completely independent:
 "C/C++ Editor", "Editing Java Source", "Editing Properties Files" vs "In Console"
And in fact without ANSI Support binding to Ctrl+Shift+C, there are still conflicts reported between the other bindings.

I've also tried the functionality.
And it all works properly, in console / java / C++ /  properties editor.

So I am quite sure this is a false positive on Linux.

I can:
  1. spend some time dig in the code that checks for the conflicts, find the problem and point to it :-)
  2. just file a bug claiming that the validation is wrong and leave it to someone else

But the questions: should I enable Ctrl+Shift+C for ANSI Settings, confident that is a false positive, Linux only, and tested that it works? Or play it safe and not assign any hotkeys?

**Comment by mihnita** [comment] 2022-08-10 02:45
@iloveeclipse Any opinion please?
Thank you!
M

**Comment by iloveeclipse** [comment] 2022-08-10 04:40
> I am quite sure this is a false positive on Linux.

 It is not only "false positive" reporting. The problem is that if that happens, the affected keybindings do not work afterwards. So we have to understand where the problem is coming from and fix that.

If that is Linux only, my guess would be different context activation timings, because of possible different key processing events order on GTK.

As long as we have the broken bindings, I would not enable them. The "rest" of Eclipse doesn't trigger binding conflicts, so it must be something special in the Console.

**Comment by mihnita** [comment] 2022-08-10 14:55
> The "rest" of Eclipse doesn't trigger binding conflicts

There are binding conflicts in the official m2 download.
Directly as a package, not with the installed.
Got "[Eclipse IDE for Java Developers, Linux [x86_64]](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2022-09/M2/eclipse-java-2022-09-M2-linux-gtk-x86_64.tar.gz)

Unpacked and started it.

The results are:
```
eclipse.buildId=4.25.0.I20220728-1800
java.version=17.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

org.eclipse.jface
Warning
Wed Aug 10 07:50:39 PDT 2022
A conflict occurred for ALT+SHIFT+R:
Binding(ALT+SHIFT+R,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.rename.element,Rename - Refactoring ,
		Rename the selected element,
		Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
		WorkbenchHandlerServiceHandler("org.eclipse.jdt.ui.edit.text.java.rename.element"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+SHIFT+R,
	ParameterizedCommand(Command(org.eclipse.ui.edit.rename,Rename,
		Rename the selected item,
		Category(org.eclipse.ui.category.file,File,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.ui.edit.rename"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
```
and 
```
eclipse.buildId=4.25.0.I20220728-1800
java.version=17.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

org.eclipse.jface
Warning
Wed Aug 10 07:50:39 PDT 2022
A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.jdt.ui.navigate.open.type"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.lsp4e.symbolinworkspace"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
```

Nothing extra installed. And the ANSI support is not in M2.

**Comment by mihnita** [comment] 2022-08-10 15:02
> the affected keybindings do not work afterwards

I've tested, and they work.

I can test again on all platforms, and test the ANSI copy, and "Toggle comments"

BTW, if looks a bit like "Toggle comments" is grabbing a bit too many hotkeys? :-)
It takes Ctrl+/, Ctrl+7, and Ctrl+Shift+C

And Ctrl+Shift+C is Copy in all the Linux and MacOS console / terminal applications that I know of
(you can't use Ctrl+C in a terminal app, because it sends a `SIGINT` signal, which cancels or terminates the currently-running program)

Is there a way to "bribe" the owners of "Toggle comments" to release Ctrl+Shift+C?
;-)

**Comment by mihnita** [comment] 2022-08-17 06:02
@iloveeclipse 

Considering that right now the bindings are removed, what should we do about this bug?
1. Close as resolved
2. Want me to spend some time to figure out why there is a conflict reported on MacOS, but not on Win?

Thanks,
M.

**Comment by iloveeclipse** [comment] 2022-08-17 06:15
I do not plan to work on this and do not see strong need for dedicated shortcuts, so if you are OK with current state,  you can close this ticket.

**Closed** 2022-09-15 13:56 UTC
