### ISSUE TITLE
[Test] testBug421303_StreamProcessingDeadlock failure on Windows

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-platform/eclipse.platform.debug#5] opened 2022-04-14 16:30 UTC
https://download.eclipse.org/eclipse/downloads/drops4/I20220414-0120/testresults/html/org.eclipse.debug.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11.html
Test triggered errors in IOConsole: java.util.stream.ReferencePipeline$Head@7269674d

java.lang.AssertionError: Test triggered errors in IOConsole: java.util.stream.ReferencePipeline$Head@7269674d
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.eclipse.debug.tests.console.IOConsoleTests.assertNoError(IOConsoleTests.java:129)
at org.eclipse.debug.tests.console.IOConsoleTests.tearDown(IOConsoleTests.java:120)

Relevant bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=421303
From Log: Stack Trace
	at org.eclipse.swt.internal.win32.OS.GetCharacterPlacement(Native Method)
	at org.eclipse.swt.internal.BidiUtil.resolveTextDirection(BidiUtil.java:502)
	at org.eclipse.swt.graphics.TextLayout.itemize(TextLayout.java:2766)
	at org.eclipse.swt.graphics.TextLayout.computeRuns(TextLayout.java:270)
	at org.eclipse.swt.graphics.TextLayout.getLineCount(TextLayout.java:1918)
	at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:1270)
	at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:908)
	at org.eclipse.swt.custom.StyledTextRenderer.calculate(StyledTextRenderer.java:298)
	at org.eclipse.swt.custom.StyledTextRenderer.calculateClientArea(StyledTextRenderer.java:328)
	at org.eclipse.swt.custom.StyledText.resetCache(StyledText.java:8341)
	at org.eclipse.swt.custom.StyledText.handleTextChanged(StyledText.java:6552)
	at org.eclipse.swt.custom.StyledText$5.textChanged(StyledText.java:5912)
	at org.eclipse.ui.internal.console.ConsoleDocumentAdapter.documentChanged(ConsoleDocumentAdapter.java:588)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged2(AbstractDocument.java:748)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:717)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:701)
	at org.eclipse.jface.text.AbstractDocument.fireDocumentChanged(AbstractDocument.java:775)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1100)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1118)
	at org.eclipse.ui.internal.console.ConsoleDocument.replace(ConsoleDocument.java:74)
	at org.eclipse.ui.internal.console.IOConsolePartitioner$QueueProcessingJob.applyOutputToDocument(IOConsolePartitioner.java:1140)
	at org.eclipse.ui.internal.console.IOConsolePartitioner$QueueProcessingJob.applyStreamOutput(IOConsolePartitioner.java:963)
	at org.eclipse.ui.internal.console.IOConsolePartitioner$QueueProcessingJob.processPendingPartitions(IOConsolePartitioner.java:800)
	at org.eclipse.ui.internal.console.IOConsolePartitioner$QueueProcessingJob.runInUIThread(IOConsolePartitioner.java:758)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.ui.progress.UIJob$$Lambda$628/0x00000001008f9040.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4053)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3658)
	at org.eclipse.debug.tests.TestUtil.processUIEvents(TestUtil.java:77)
	at org.eclipse.debug.tests.TestUtil.waitForJobs(TestUtil.java:209)
	at org.eclipse.debug.tests.TestUtil.waitForJobs(TestUtil.java:185)
	at org.eclipse.debug.tests.console.IOConsoleTestUtil.waitForScheduledJobs(IOConsoleTestUtil.java:699)
	at org.eclipse.debug.tests.console.IOConsoleTests.closeConsole(IOConsoleTests.java:194)
	at org.eclipse.debug.tests.console.IOConsoleTests.testBug421303_StreamProcessingDeadlock(IOConsoleTests.java:918)

**Comment by SarikaSinha** [comment] 2022-04-18 09:30
https://download.eclipse.org/eclipse/downloads/drops4/I20220417-1800/testresults/html/org.eclipse.debug.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11.html

**Comment by SarikaSinha** [comment] 2022-04-18 11:55
https://download.eclipse.org/eclipse/downloads/drops4/I20220415-1800/testresults/html/org.eclipse.debug.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11.html
@jukzi Can this be caused due to "Slow logging"  changes done recently as I never saw this failing in years.

**Comment by jukzi** [comment] 2022-04-18 17:16
> @jukzi Can this be caused due to "Slow logging" changes

no. I can locally reproduce the error sometimes:
org.eclipse.debug.tests.TestUtil.dumpRunningOrWaitingJobs(String, List<Job>) line:247
	TestUtil.waitForJobs(String, long, long, Object...) line:230
	TestUtil.waitForJobs(String, long, long) line: 185	
	IOConsoleTestUtil.waitForScheduledJobs() line: 699	
	IOConsoleTests.closeConsole(IOConsoleTestUtil, String...) line: 196	
	IOConsoleTests.testBug421303_StreamProcessingDeadlock() line: 920	
just stating that some job 'Animation start(41)'/org.eclipse.ui.internal.progress.TaskBarProgressManager$1 did not finish within 2000ms

that speed regression in org.eclipse.swt.internal.BidiUtil.resolveTextDirection(String) (seen in the stacktrace you gave)  is more likely due to commit 0d622fbfd301229f9bb9ed13043811777afeb29d
Author: Niraj Modi <92304759+niraj-modi@users.noreply.github.com> 2022-04-13 14:41:48
"Mixed RTL text(with LTR) is not rendered correctly in StyledText widget (#45)"

`// Do-not break here, instead scan the complete text for any RTL possibility`

**Comment by iloveeclipse** [comment] 2022-04-18 17:28
@niraj-modi  I haven't checked in the IDE : could it be, we have now a performance issue with StyledText, because of https://github.com/eclipse-platform/eclipse.platform.swt/pull/45 ?

**Comment by niraj-modi** [comment] 2022-04-19 08:55
> @niraj-modi I haven't checked in the IDE : could it be, we have now a performance issue with StyledText, because of [eclipse-platform/eclipse.platform.swt#45](https://github.com/eclipse-platform/eclipse.platform.swt/pull/45) ?

Above SWT fix makes BidiUtil#resolveTextDirection() method to scan the complete line for any RightToLeft character search if present(unlike the old behavior), which is inline with it's JavaDoc and is required for StyledText to correctly display lines(with mix of LeftToRight and RightToLeft characters)

With cursory look I notice the failing performance JUnit in platform.debug does print some 200k characters per line and doing it in parallel as well. Will discuss/investigate what is required here.

BTW, I notice this is a random failure, it's passing occasionally as well:
https://download.eclipse.org/eclipse/downloads/drops4/I20220416-1800/testresults/html/org.eclipse.debug.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11.html

**Comment by niraj-modi** [comment] 2022-04-20 07:54
Attempted a fix in SWT end to improve implementation for BidiUtil#resolveTextDirection() via below commit:
https://github.com/eclipse-platform/eclipse.platform.swt/pull/57 

Looks like this as improved the situation for this performance test-case, I don't see it failing in latest IBuild:
https://download.eclipse.org/eclipse/downloads/drops4/I20220419-1800/testresults/html/org.eclipse.debug.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11.html

@jukzi 
@SarikaSinha 
Before we can close on this, please double check this JUnit test locally & confirm, Thanks!

**Comment by jukzi** [comment] 2022-04-20 08:05
i tested in debug mode, that the branch that you added is never taken during the failing test => it's not an improvement

**Comment by jukzi** [comment] 2022-04-20 08:15
on the other hand i also  tested that the former "break" branch is also never taken... so removing the "break" was not issue.

**Closed** 2022-05-06 14:29 UTC
